import Head from "next/head";

const Header = () => {
  return (
    <div>
      <Head>
        <title>Alexis - Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/x-icon" href="/favicon-1.jpg" />
      </Head>
    </div>
  );
};

export default Header;
